# NumPy


---

## Ejercicio 1 — Crear arrays

Importá NumPy utilizando el alias convencional `np`.

Creá una lista de Python con los números del 1 al 5 y, a partir de ella, creá un array de NumPy.

Imprimí ambos y sus respectivos tipos.

In [ ]:
import numpy as np

numbers = [1, 2, 3, 4, 5]

numbers_np = np.array(numbers)

print(type(numbers), numbers)
print(type(numbers_np), numbers_np)

---

## Ejercicio 2 — Tipos de datos

Creá un array con los valores `[10, 20, 30, 40]`.

Consultá:
- El tipo del objeto.
- El tipo de los elementos almacenados en el array.

In [ ]:
import numpy as np

numbers = np.array([10, 20, 30, 40])

print("numbers type:", type(numbers))
print("elements type:", numbers.dtype)

---

## Ejercicio 3 — Shape y dimensiones

Creá el array bidimensional `[[1, 2, 3], [4, 5, 6]]`.

Obtené:
- Su forma.
- Su cantidad de dimensiones.
- Su cantidad total de elementos.

In [ ]:
import numpy as np

numbers = np.array([[1, 2, 3], [4, 5, 6]])

print("shape:", numbers.shape)
print("dimensions:", numbers.ndim)
print("size:", numbers.size)

---

## Ejercicio 4 — Indexación unidimensional

Creá `[10, 20, 30, 40, 50]` como array.

Mostrá el primer elemento, el último y el tercero.

In [ ]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers[0])
print(numbers[-1])
print(numbers[2])

---

## Ejercicio 5 — Slicing unidimensional

Usando `[10, 20, 30, 40, 50]`, obtené mediante slicing:
- Los primeros tres elementos.
- Desde el tercer elemento hasta el final.
- Todos excepto el primero y el último.

In [ ]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers[:3])
print(numbers[2:])
print(numbers[1:-1])

---

## Ejercicio 6 — Indexación bidimensional

Creá `[[10, 20, 30], [40, 50, 60], [70, 80, 90]]`.

Accedé individualmente a `10`, `50` y `90` usando indexación de NumPy.

In [ ]:
import numpy as np

numbers = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(numbers[0, 0])
print(numbers[1, 1])
print(numbers[2, 2])

---

## Ejercicio 7 — Slicing bidimensional

Utilizando el array anterior, obtené `[[10, 20], [40, 50]]` mediante slicing, sin crear manualmente un nuevo array.

In [ ]:
import numpy as np

numbers = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(numbers[:2, :2])

---

## Ejercicio 8 — Operaciones vectorizadas

Creá `[1, 2, 3, 4, 5]` como array de NumPy.

Sin `for`, obtené nuevos arrays con:
- Todos los números multiplicados por 2.
- Todos elevados al cuadrado.
- 10 sumado a cada número.

In [ ]:
import numpy as np

numbers = np.array([1, 2, 3, 4, 5])

print(numbers * 2)
print(numbers ** 2)
print(numbers + 10)

---

## Ejercicio 9 — Operaciones entre arrays

Creá `a = [1, 2, 3]` y `b = [10, 20, 30]` como arrays.

Calculá elemento a elemento `a + b` y `a * b`.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)
print(a * b)

---

## Ejercicio 10 — Universal Functions

Creá `[1, 4, 9, 16, 25]`.

Utilizando funciones de NumPy, obtené la raíz cuadrada y el cuadrado de cada elemento.

In [ ]:
import numpy as np

numbers = np.array([1, 4, 9, 16, 25])

print(np.sqrt(numbers))
print(np.square(numbers))

---

## Ejercicio 11 — Filtros

Creá `[10, 25, 30, 45, 50, 65, 70]`.

Obtené un nuevo array con únicamente los valores mayores a 40. No utilices `for`.

In [43]:
import numpy as np

numbers = np.array([10, 25, 30, 45, 50, 65, 70])

print(numbers[numbers > 40])

[45 50 65 70]


---

## Ejercicio 12 — Filtros con múltiples condiciones

Utilizando el array anterior, obtené solamente los números mayores o iguales a 30 y menores o iguales a 60. No utilices `for`.

In [52]:
import numpy as np

numbers = np.array([10, 25, 30, 45, 50, 65, 70])

print(numbers[(numbers >= 30) & (numbers <= 60)])

[30 45 50]


---

## Ejercicio 13 — Funciones de agregación

Creá `[10, 20, 30, 40, 50]`.

Calculá suma, promedio, mínimo y máximo.

In [59]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(np.sum(numbers))
print(np.mean(numbers))
print(np.min(numbers))
print(np.max(numbers))

150
30.0
10
50


---

## Ejercicio 14 — Agregaciones por eje

Creá `[[10, 20, 30], [40, 50, 60]]`.

Calculá:
- La suma total.
- La suma de cada columna.
- La suma de cada fila.

Observá cómo cambia el resultado según el eje.

In [62]:
import numpy as np

numbers = np.array([[10, 20, 30], 
                    [40, 50, 60]])

print(np.sum(numbers))
print(np.sum(numbers, axis=0))
print(np.sum(numbers, axis=1))

210
[50 70 90]
[ 60 150]
